language: cpp
sudo: required
addons:
  apt:
    packages:
      - libsdl-dev
      - libsdl-mixer1.2-dev
      - libsdl-gfx1.2-dev
      - libsdl-ttf2.0-dev
      - libglew-dev
compiler:
  - gcc
  - clang
script:
  - autoreconf -fiv
  - ./configure
  - make
  - sudo make install
